version: '2'

networks:
    default:
        external:
            name: dev

services:
  
    php:
        # image: toxaco/signaturedockerenv:latest #master branch
        build: ./ #develop branch
        container_name: signature
        environment:
            VIRTUAL_HOST:   "dev.loan.co.uk"
            PHP_IDE_CONFIG: "serverName=loan.php"
            CERT_NAME:      "dev"
        ports:
            - "24890:24890" #websocket port
            - "24891:24891" #websocket port
            - "24892:24892" #websocket port
        volumes:
           - ./../application/:/var/www/html:cached #for Mac
           - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:cached #for Mac
           - ./config/nginx.conf:/etc/nginx/nginx.conf:cached #for Mac
           - ./cert/:/etc/nginx/certs:cached
           # - ./config/crontab:/etc/crontab:cached #for Mac
        command:
           - "/usr/bin/supervisord"

    portainer:
        image: portainer/portainer
        container_name: management
        ports:
            - "9900:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:cached #for Mac
            - ./data/portainer:/data:cached #for Mac

    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: proxy
        privileged: true
        environment:
            DEFAULT_HOST: "dev.loan.co.uk"
            CERT_NAME: "dev"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:cached #for Mac
            - ./config/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:cached #for Mac
            - ./cert/:/etc/nginx/certs:cached #Update Dockerfile as well to make sure websockets works

    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql:cached #for Mac
            # Ensure MySql 5.7 is running in "disable strict SQL mod". [03/2018]
            - ./config/mysqlConfig/:/etc/mysql/conf.d/:cached #for Mac
        environment:
            MYSQL_ROOT_PASSWORD: root

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
        container_name: elasticsearch
        privileged: true
        ports:
            - "9200:9200"

    # redis:
    #     image: redis:5-alpine
    #     container_name: redis
    #     ports:
    #         - "6379:6379"

    # mariadb:
    #     image: mariadb
    #     container_name: mariadb
    #     restart: always
    #     ports:
    #         - "3307:3306"
    #     volumes:
    #         - ./data/mariadb:/var/lib/mysql:cached #for Mac
    #         # Ensure MySql 5.7 is running in "disable strict SQL mod". [03/2018]
    #         # - ./config/mysqlConfig/:/etc/mysql/conf.d/:cached #for Mac
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root

    # blackfire:
    #     image: blackfire/blackfire
    #     container_name: blackfire
    #     ports:
    #         - "8707:8707"
    #     environment:
    #         BLACKFIRE_CLIENT_ID: "47aba20d-ba22-4160-b16a-e87f8bb55d38"
    #         BLACKFIRE_CLIENT_TOKEN: "c5b80eebaab1ad94c85368d0955a653ebb8d60469fa868db6aaafdc0b2e0493e"
    #         BLACKFIRE_SERVER_ID: "26ee3109-d139-4bc6-bccd-68276b85596e"
    #         BLACKFIRE_SERVER_TOKEN: "ed714c208eae8d61075e432b02f86bb29d518f5c7813c277f29e2d694ca4a0d3"
